const views={
 dashboard:{title:'Business dashboard',html:`<section class="hero"><span class="status">READY TO CONFIGURE</span><h2>Your AI workspace for business</h2><p class="muted">Provision, personalize, test and operate dedicated AI assistants from one control plane.</p></section><div class="grid"><article class="card"><h3>Assistant</h3><p class="muted">Identity, personality, role, rules and escalation.</p><div class="metric">Draft</div></article><article class="card"><h3>Knowledge</h3><p class="muted">Websites, documents, FAQs, catalogs and policies.</p><div class="metric">0 sources</div></article><article class="card"><h3>Channels</h3><p class="muted">Shared context across Web, Telegram and WhatsApp.</p><div class="metric">0 active</div></article></div>`},
 company:{title:'Company',html:`<section class="hero"><h2>Company profile</h2><p class="muted">Business identity, contact details, locations, services and operating rules will be configured here.</p></section>`},
 assistant:{title:'Assistant',html:`<section class="hero"><h2>Personalized assistant</h2><p class="muted">Define name, avatar, greeting, personality, tone, languages, business role, instructions and escalation behavior.</p></section>`},
 knowledge:{title:'Knowledge',html:`<section class="hero"><h2>Knowledge layer</h2><p class="muted">Connect website content and business documents. Unknown information remains unknown and can be escalated to a human.</p></section>`},
 channels:{title:'Channels',html:`<section class="hero"><h2>Omnichannel workspace</h2><p class="muted">Prepare Web, Telegram and WhatsApp with tenant-isolated identities and shared assistant context.</p></section>`},
 customers:{title:'Customers',html:`<section class="hero"><h2>Customers</h2><p class="muted">Customer identities and conversation context will remain isolated by business and assistant.</p></section>`},
 projects:{title:'Projects',html:`<section class="hero"><h2>Projects</h2><p class="muted">Organize assistant deployments, business initiatives and implementation work.</p></section>`},
 automation:{title:'Automation',html:`<section class="hero"><h2>Automation</h2><p class="muted">Design controlled workflows for notifications, follow-ups, routing and operational tasks.</p></section>`},
 analytics:{title:'Analytics',html:`<section class="hero"><h2>Analytics</h2><p class="muted">Monitor assistant usage, channel activity, readiness and business outcomes.</p></section>`},
 readiness:{title:'AI Readiness',html:`<section class="hero"><span class="status">DRAFT</span><h2>Readiness lifecycle</h2><p class="muted">DRAFT → CONFIGURING → TESTING → READY → ACTIVE. Changes that require review are marked NEEDS_REVIEW.</p></section>`}
};
function render(){const key=(location.hash||'#dashboard').slice(1);const view=views[key]||views.dashboard;document.title=`${view.title} — Bitey Enterprise`;document.querySelector('#page-title').textContent=view.title;document.querySelector('#app').innerHTML=view.html;document.querySelectorAll('.sidebar nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${key}`))}
window.addEventListener('hashchange',render);render();
